
project_id = "fqitlkgxqmhzqbhqazyc"
[functions.facebook-ads]
verify_jwt = false

[functions.facebook-sync-data]
verify_jwt = false

[functions.facebook-cron-sync]
verify_jwt = false

[functions.facebook-fill-missing]
verify_jwt = false

[functions.get-metrics]
verify_jwt = false
