
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqitlkgxqmhzqbhqazyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxaXRsa2d4cW1oenFiaHFhenljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTIwMDcsImV4cCI6MjA1ODI2ODAwN30.8KGMqvU7zPQHDqgWjqHGbFXYCRPdys24PLeQFw_SyzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
